apiVersion: v1
kind: ServiceAccount
metadata:
  name: logs-proxy
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logs-proxy-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logs-proxy-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: logs-proxy
    namespace: default
roleRef:
  kind: Role
  name: logs-proxy-role
  apiGroup: rbac.authorization.k8s.io
